/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
//#include "system_stm32f4xx.h"
#include "ucg.h"
#include "timer.h"
#include "Ucglib.h"

static ucg_t ucg;

int main(void)
{
    /* Loop forever */
		SystemCoreClockUpdate();
		TimerInit();
	  // 👇 thêm đoạn này
	  Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
	  ucg_ClearScreen(&ucg);

	  ucg_SetFont(&ucg, ucg_font_ncenR18_tf);
	  ucg_SetColor(&ucg, 0, 255, 255, 255);
	  ucg_SetColor(&ucg, 1, 0, 0, 0);
	  ucg_SetRotate180(&ucg);

	  ucg_DrawString(&ucg, 0, 12, 0, "I love Embedded");
	  ucg_DrawString(&ucg, 0, 26, 0, "Programming");
	  while(1)
	  {
	      processTimerScheduler();
	  }
}
